#include "newsettings.h"

void NewSettings::setupKeys() {

    addKey("ab/lineLength", 1600);
    addKey("ardMac/hydLowerTime", 4);
    addKey("ardMac/hydRaiseTime", 3);
    addKey("ardMac/isDanFoss", false);
    addKey("ardMac/isHydEnabled", 0);
    addKey("ardMac/setting0", 0);
    addKey("ardMac/user1", 1);
    addKey("ardMac/user2", 2);
    addKey("ardMac/user3", 3);
    addKey("ardMac/user4", 4);
    addKey("ardSteer/ardSteerMaxPulseCounts", 3);
    addKey("ardSteer/maxSpeed", 20);
    addKey("ardSteer/minSpeed", 0);
    addKey("ardSteer/setting0", 56);
    addKey("ardSteer/setting1", 0);
    addKey("ardSteer/setting2", 0);
    addKey("as/ackerman", 100);
    addKey("as/countsPerDegree", 110);
    addKey("as/deadZoneDelay", 5);
    addKey("as/deadZoneDistance", 1);
    addKey("as/deadZoneHeading", 10);
    addKey("as/functionSpeedLimit", 12);
    addKey("as/guidanceLookAheadTime", 1.5);
    addKey("as/highSteerPWM", 180);
    addKey("as/isAutoSteerAutoOn", false);
    addKey("as/isConstantContourOn", false);
    addKey("as/isSteerInReverse", false);
    addKey("as/Kp", 50);
    addKey("as/lowSteerPWM", 30);
    addKey("as/maxSteerSpeed", 15);
    addKey("as/minSteerPWM", 25);
    addKey("as/minSteerSpeed", 0);
    addKey("as/modeMultiplierStanley", 0.6);
    addKey("as/modeTime", 1);
    addKey("as/modeXTE", 0.1);
    addKey("as/numGuideLines", 10);
    addKey("as/sideHillCompensation", 0);
    addKey("as/snapDistance", 20);
    addKey("as/snapDistanceRef", 5);
    addKey("as/uTurnCompensation", 1);
    addKey("as/uTurnSmoothing", 14);
    addKey("as/wasOffset", 3);
    addKey("bnd/isDrawPivot", true);
    addKey("brand/HBrand", "AgOpenGPS");
    addKey("brand/TBrand", "AGOpenGPS");
    addKey("brand/WDBrand", "AgOpenGPS");
    addKey("cam/camLink", QString("rtsp://192.168.0.138:1945"));
    addKey("color/isMultiColorSections", false);
    addKey("color/sec01", QColor(249, 22, 10));
    addKey("color/sec02", QColor(68, 84, 254));
    addKey("color/sec03", QColor(8, 243, 8));
    addKey("color/sec04", QColor(233, 6, 233));
    addKey("color/sec05", QColor(200, 191, 86));
    addKey("color/sec06", QColor(0, 252, 246));
    addKey("color/sec07", QColor(144, 36, 246));
    addKey("color/sec08", QColor(232, 102, 21));
    addKey("color/sec09", QColor(255, 160, 170));
    addKey("color/sec10", QColor(205, 204, 246));
    addKey("color/sec11", QColor(213, 239, 190));
    addKey("color/sec12", QColor(247, 200, 247));
    addKey("color/sec13", QColor(253, 241, 144));
    addKey("color/sec14", QColor(187, 250, 250));
    addKey("color/sec15", QColor(227, 201, 249));
    addKey("color/sec16", QColor(247, 229, 215));
    addKey("display/antiAliasSamples", 0);
    addKey("display/autoDayNight", false);
    addKey("display/brightness", 40);
    addKey("display/brightnessSystem", 40);
    addKey("display/buttonOrder", "0,1,2,3,4,5,6,7");
    addKey("display/camPitch", -62);
    addKey("display/camSmooth", 50);
    addKey("display/camZoom", 9);
    addKey("display/colorDayBackground", QColor::fromRgb(245, 245, 245));
    addKey("display/colorDayBorder", QColor::fromRgb(215, 228, 242));
    addKey("display/colorDayFrame", QColor(210, 210, 230));
    addKey("display/colorFieldDay", QColor(145, 145, 145));
    addKey("display/colorFieldNight", QColor(60, 60, 60));
    addKey("display/colorNightBackground", QColor::fromRgb(50, 50, 65));
    addKey("display/colorNightBorder", QColor::fromRgb(210, 210, 230));
    addKey("display/colorNightFrame", QColor(50, 50, 65));
    addKey("display/colorSectionsDay", QColor(27, 151, 160));
    addKey("display/colorSectionsNight", QColor(27, 100, 100));
    addKey("display/colorTextDay", QColor("Black"));
    addKey("display/colorTextNight", QColor(230, 230, 230));
    addKey("display/colorVehicle", QColor("White"));
    addKey("display/customColors", "-62208,-12299010,-16190712,-1505559,-3621034,-16712458,-7330570,-1546731,-24406,-3289866,-2756674,-538377,-134768,-4457734,-1848839,-530985");
    addKey("display/customSectionColors", "-62208,-12299010,-16190712,-1505559,-3621034,-16712458,-7330570,-1546731,-24406,-3289866,-2756674,-538377,-134768,-4457734,-1848839,-530985");
    addKey("display/features", "");
    addKey("display/isAutoOffAgIO", true);
    addKey("display/isAutoStartAgIO", true);
    addKey("display/isBrightnessOn", false);
    addKey("display/isDayMode", true);
    addKey("display/isHardwareMessages", false);
    addKey("display/isKeyboardOn", true);
    addKey("display/isLineSmooth", false);
    addKey("display/isLogElevation", false);
    addKey("display/isSectionLinesOn", true);
    addKey("display/isShutDownWhenNoPower", false);
    addKey("display/isStartFullscreen", false);
    addKey("display/isSvennArrowOn", false);
    addKey("display/isTermsAccepted", false);
    addKey("display/isTextureOn", true);
    addKey("display/isVehicleImage", true);
    addKey("display/lightbarCmPerPixel", 5);
    addKey("display/lineWidth", 2);
    addKey("display/panelSimLocation", QPoint(97, 600));
    addKey("display/showBack", false);
    addKey("display/topTrackNum", false);
    addKey("display/triangleResolution", 1);
    addKey("display/useTrackZero", false);
    addKey("display/vehicleOpacity", 100);
    addKey("f/boundaryTriggerDistance", 1);
    addKey("f/currentDir", "");
    addKey("f/isRemoteWorkSystemOn", false);
    addKey("f/isSteerWorkSwitchEnabled", false);
    addKey("f/isSteerWorkSwitchManualSections", false);
    addKey("f/isWorkSwitchActiveLow", true);
    addKey("f/isWorkSwitchEnabled", false);
    addKey("f/isWorkSwitchManualSections", false);
    addKey("f/minHeadingStepDistance", 0.5);
    addKey("f/userTotalArea", 0);
    addKey("feature/isABLineOn", true);
    addKey("feature/isABSmoothOn", false);
    addKey("feature/isAgIOOn", true);
    addKey("feature/isAutoSectionOn", true);
    addKey("feature/isAutoSteerOn", true);
    addKey("feature/isBndContourOn", false);
    addKey("feature/isBoundaryOn", true);
    addKey("feature/isContourOn", true);
    addKey("feature/isCurveOn", true);
    addKey("feature/isCycleLinesOn", true);
    addKey("feature/isHeadlandOn", true);
    addKey("feature/isHideContourOn", false);
    addKey("feature/isLateralOn", true);
    addKey("feature/isManualSectionOn", true);
    addKey("feature/isOffsetFixOn", false);
    addKey("feature/isRecPathOn", false);
    addKey("feature/isSteerModeOn", true);
    addKey("feature/isTramOn", false);
    addKey("feature/isUTurnOn", true);
    addKey("feature/isWebCamOn", false);
    addKey("feature/isYouTurnOn", true);
    addKey("gps/ageAlarm", 20);
    addKey("gps/dualHeadingOffset", 0);
    addKey("gps/dualReverseDetectionDistance", 0.25);
    addKey("gps/fixFromWhichSentence", "GGA");
    addKey("gps/forwardComp", 0.15);
    addKey("gps/headingFromWhichSource", "Fix");
    addKey("gps/isRTK", false);
    addKey("gps/isRTKKillAutoSteer", false);
    addKey("gps/jumpFixAlarmDispance", 0);
    addKey("gps/minimumStepLimit", 0.05);
    addKey("gps/reverseComp", 0.3);
    addKey("gps/simLatitude", 53.4360564);
    addKey("gps/simLongitude", -111.160047);
    addKey("gps/udpWatchMSec", 50);
    addKey("headland/isSectionControlled", true);
    addKey("imu/fusionWeight2", 0.06);
    addKey("imu/invertRoll", false);
    addKey("imu/isDualAsIMU", false);
    addKey("imu/isHeadingCorrectionFromAutoSteer", false);
    addKey("imu/isReverseOn", true);
    addKey("imu/pitchZeroX16", 0);
    addKey("imu/rollFilter", 0);
    addKey("imu/rollZero", 0);
    addKey("jobMenu/location", QPoint(200, 200));
    addKey("jobMenu/size", "640, 530");
    addKey("key/hotKeys", "ACFGMNPTYVW12345678");
    addKey("menu/isCompassOn", true);
    addKey("menu/isGridOn", true);
    addKey("menu/isLightBarNotSteerBar", false);
    addKey("menu/isLightBarOn", true);
    addKey("menu/isMetric", true);
    addKey("menu/isOGLZoom", false);
    addKey("menu/isPureOn", true);
    addKey("menu/isSideGuideLines", false);
    addKey("menu/isSimulatorOn", true);
    addKey("menu/isSkyOn", true);
    addKey("menu/isSpeedoOn", false);
    addKey("relay/pinConfig", toVariant(default_relay_pinConfig), NewSettings::VECTOR_OF_INTS);
    addKey("section/isFast", false);
    addKey("section/position1", -2);
    addKey("section/position10", 0);
    addKey("section/position11", 0);
    addKey("section/position12", 0);
    addKey("section/position13", 0);
    addKey("section/position14", 0);
    addKey("section/position15", 0);
    addKey("section/position16", 0);
    addKey("section/position17", 0);
    addKey("section/position2", -1);
    addKey("section/position3", 1);
    addKey("section/position4", 2);
    addKey("section/position5", 0);
    addKey("section/position6", 0);
    addKey("section/position7", 0);
    addKey("section/position8", 0);
    addKey("section/position9", 0);
    addKey("seed/blockageIsOn", false);
    addKey("seed/blockCountMax", 1000);
    addKey("seed/blockCountMin", 100);
    addKey("seed/blockRow1", 16);
    addKey("seed/blockRow2", 16);
    addKey("seed/blockRow3", 16);
    addKey("seed/blockRow4", 0);
    addKey("seed/numRows", 32);
    addKey("sound/autoSteerSound", true);
    addKey("sound/isHydLiftOn", true);
    addKey("sound/isSectionOn", true);
    addKey("sound/isUturnOn", true);
    addKey("tool/defaultSectionWidth", 2);
    addKey("tool/isDirectionMarkers", true);
    addKey("tool/isDisplayTramControl", true);
    addKey("tool/isSectionOffWhenOut", true);
    addKey("tool/isSectionsNotZones", true);
    addKey("tool/isTBT", false);
    addKey("tool/isToolFront", false);
    addKey("tool/isToolRearFixed", false);
    addKey("tool/isToolTrailing", true);
    addKey("tool/isTramOuterInverted", false);
    addKey("tool/numSectionsMulti", 20);
    addKey("tool/sectionWidthMulti", 0.5);
    addKey("tool/toolTrailingHitchLength", -2.5);
    addKey("tool/trailingToolToPivotLength", 0);
    addKey("tool/zones", toVariant(default_zones), NewSettings::VECTOR_OF_INTS);
    addKey("tram/alpha", 0.8);
    addKey("tram/basedOn", 0);
    addKey("tram/isTramOnBackBuffer", true);
    addKey("tram/offset", 0);
    addKey("tram/passes", 1);
    addKey("tram/skips", 0);
    addKey("tram/snapAdj", 1);
    addKey("tram/width", 24);
    addKey("vehicle/antennaHeight", 3);
    addKey("vehicle/antennaOffset", 0);
    addKey("vehicle/antennaPivot", 0.1);
    addKey("vehicle/goalPointAcquireFactor", 0.9);
    addKey("vehicle/goalPointLookAhead", 3);
    addKey("vehicle/goalPointLookAheadHold", 3);
    addKey("vehicle/goalPointLookAheadMult", 1.5);
    addKey("vehicle/hitchLength", -1);
    addKey("vehicle/hydraulicLiftLookAhead", 2);
    addKey("vehicle/isMachineControlToAutoSteer", false);
    addKey("vehicle/isPivotBehindAntenna", true);
    addKey("vehicle/isStanleyUsed", false);
    addKey("vehicle/isSteerAxleAhead", true);
    addKey("vehicle/lookAheadMinimum", 2);
    addKey("vehicle/maxAngularVelocity", 0.64);
    addKey("vehicle/maxSteerAngle", 30);
    addKey("vehicle/minCoverage", 100);
    addKey("vehicle/minTurningRadius", 8.1);
    addKey("vehicle/numSections", 3);
    addKey("vehicle/panicStopSpeed", 0);
    addKey("vehicle/purePursuitIntegralGainAB", 0);
    addKey("vehicle/slowSpeedCutoff", 0.5);
    addKey("vehicle/stanleyDistanceErrorGain", 1);
    addKey("vehicle/stanleyHeadingErrorGain", 1);
    addKey("vehicle/stanleyIntegralDistanceAwayTriggerAB", 0.25);
    addKey("vehicle/stanleyIntegralGainAB", 0);
    addKey("vehicle/tankTrailingHitchLength", -3);
    addKey("vehicle/toolLookAheadOff", 0.5);
    addKey("vehicle/toolLookAheadOn", 1);
    addKey("vehicle/toolOffDelay", 0);
    addKey("vehicle/toolOffset", 0);
    addKey("vehicle/toolOverlap", 0);
    addKey("vehicle/toolWidth", 4);
    addKey("vehicle/trackWidth", 1.9);
    addKey("vehicle/vehicleName", QString("Default Vehicle"));
    addKey("vehicle/vehicleType", 0);
    addKey("vehicle/wheelbase", 3.3);
    addKey("window/abDrawLocation", QRect(0,0,1022,742));
    addKey("window/bingMapSize", QRect(0,0,965,700));
    addKey("window/bingZoom", 15);
    addKey("window/buildTracksLocation", QPoint(40, 40));
    addKey("window/formNudgeLocation", QRect(0,0,200, 200));
    addKey("window/gridLocation", QPoint(20, 20));
    addKey("window/gridSize", QPoint(400, 400));
    addKey("window/headAcheSize", "1022, 742");
    addKey("window/headlineSize", "1022, 742");
    addKey("window/isKioskMode", false);
    addKey("window/isShutdownComputer", false);
    addKey("window/location", QPoint(30, 30));
    addKey("window/mapBndSize", "1022, 742");
    addKey("window/maximized", false);
    addKey("window/minimized", false);
    addKey("window/quickABLocation", QPoint(100, 100));
    addKey("window/rateMapSize", "1022, 742");
    addKey("window/rateMapZoom", 15);
    addKey("window/size", "1005, 730");
    addKey("window/steerSettingsLocation", QPoint(40, 40));
    addKey("window/tramLineSize", "921, 676");
    addKey("youturn/distanceFromBoundary", 2);
    addKey("youturn/extensionLength", 20);
    addKey("youturn/radius", 8.1);
    addKey("youturn/skipWidth", 1);
    addKey("youturn/style", 0);
    addKey("youturn/toolWidths", 2);
    addKey("youturn/youMoveDistance", 0.25);
}

